#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := http-client

# EXTRA_COMPONENT_DIRS = $(HOME)/esp/projects/esp8266/wifi_station/main

include $(IDF_PATH)/make/project.mk

